In [3]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

In [4]:
df = pd.read_csv(
    "../data/raw/DataCoSupplyChainDataset.csv",
    encoding="latin-1",
    sep=","
)

df.head()

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,Customer Country,Customer Email,Customer Fname,Customer Id,Customer Lname,Customer Password,Customer Segment,Customer State,Customer Street,Customer Zipcode,Department Id,Department Name,Latitude,Longitude,Market,Order City,Order Country,Order Customer Id,order date (DateOrders),Order Id,Order Item Cardprod Id,Order Item Discount,Order Item Discount Rate,Order Item Id,Order Item Product Price,Order Item Profit Ratio,Order Item Quantity,Sales,Order Item Total,Order Profit Per Order,Order Region,Order State,Order Status,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,Puerto Rico,XXXXXXXXX,Cally,20755,Holloway,XXXXXXXXX,Consumer,PR,5365 Noble Nectar Island,725.0,2,Fitness,18.251453,-66.037056,Pacific Asia,Bekasi,Indonesia,20755,1/31/2018 22:56,77202,1360,13.110000,0.04,180517,327.75,0.29,1,327.75,314.640015,91.250000,Southeast Asia,Java Occidental,COMPLETE,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2/3/2018 22:56,Standard Class
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,Puerto Rico,XXXXXXXXX,Irene,19492,Luna,XXXXXXXXX,Consumer,PR,2679 Rustic Loop,725.0,2,Fitness,18.279451,-66.037064,Pacific Asia,Bikaner,India,19492,1/13/2018 12:27,75939,1360,16.389999,0.05,179254,327.75,-0.80,1,327.75,311.359985,-249.089996,South Asia,Rajastán,PENDING,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/18/2018 12:27,Standard Class
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,EE. UU.,XXXXXXXXX,Gillian,19491,Maldonado,XXXXXXXXX,Consumer,CA,8510 Round Bear Gate,95125.0,2,Fitness,37.292233,-121.881279,Pacific Asia,Bikaner,India,19491,1/13/2018 12:06,75938,1360,18.030001,0.06,179253,327.75,-0.80,1,327.75,309.720001,-247.779999,South Asia,Rajastán,CLOSED,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/17/2018 12:06,Standard Class
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,EE. UU.,XXXXXXXXX,Tana,19490,Tate,XXXXXXXXX,Home Office,CA,3200 Amber Bend,90027.0,2,Fitness,34.125946,-118.291016,Pacific Asia,Townsville,Australia,19490,1/13/2018 11:45,75937,1360,22.940001,0.07,179252,327.75,0.08,1,327.75,304.809998,22.860001,Oceania,Queensland,COMPLETE,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/16/2018 11:45,Standard Class
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,Puerto Rico,XXXXXXXXX,Orli,19489,Hendricks,XXXXXXXXX,Corporate,PR,8671 Iron Anchor Corners,725.0,2,Fitness,18.253769,-66.037048,Pacific Asia,Townsville,Australia,19489,1/13/2018 11:24,75936,1360,29.500000,0.09,179251,327.75,0.45,1,327.75,298.250000,134.210007,Oceania,Queensland,PENDING_PAYMENT,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 11:24,Standard Class

In [5]:
df.shape

(180519, 53)

In [6]:
df.columns.to_list()

['Type',
 'Days for shipping (real)',
 'Days for shipment (scheduled)',
 'Benefit per order',
 'Sales per customer',
 'Delivery Status',
 'Late_delivery_risk',
 'Category Id',
 'Category Name',
 'Customer City',
 'Customer Country',
 'Customer Email',
 'Customer Fname',
 'Customer Id',
 'Customer Lname',
 'Customer Password',
 'Customer Segment',
 'Customer State',
 'Customer Street',
 'Customer Zipcode',
 'Department Id',
 'Department Name',
 'Latitude',
 'Longitude',
 'Market',
 'Order City',
 'Order Country',
 'Order Customer Id',
 'order date (DateOrders)',
 'Order Id',
 'Order Item Cardprod Id',
 'Order Item Discount',
 'Order Item Discount Rate',
 'Order Item Id',
 'Order Item Product Price',
 'Order Item Profit Ratio',
 'Order Item Quantity',
 'Sales',
 'Order Item Total',
 'Order Profit Per Order',
 'Order Region',
 'Order State',
 'Order Status',
 'Order Zipcode',
 'Product Card Id',
 'Product Category Id',
 'Product Description',
 'Product Image',
 'Product Name',
 'Product Price',
 'Product Status',
 'shipping date (DateOrders)',
 'Shipping Mode']

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 53 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Type                           180519 non-null  str
 1   Days for shipping (real)       180519 non-null  int64
 2   Days for shipment (scheduled)  180519 non-null  int64
 3   Benefit per order              180519 non-null  float64
 4   Sales per customer             180519 non-null  float64
 5   Delivery Status                180519 non-null  str
 6   Late_delivery_risk             180519 non-null  int64
 7   Category Id                    180519 non-null  int64
 8   Category Name                  180519 non-null  str
 9   Customer City                  180519 non-null  str
 10  Customer Country               180519 non-null  str
 11  Customer Email                 180519 non-null  str
 12  Customer Fname                 180519 non-null  str
 13  Customer Id                    180519 non-null  int64
 14  Customer Lname                 180511 non-null  str
 15  Customer Password              180519 non-null  str
 16  Customer Segment               180519 non-null  str
 17  Customer State                 180519 non-null  str
 18  Customer Street                180519 non-null  str
 19  Customer Zipcode               180516 non-null  float64
 20  Department Id                  180519 non-null  int64
 21  Department Name                180519 non-null  str
 22  Latitude                       180519 non-null  float64
 23  Longitude                      180519 non-null  float64
 24  Market                         180519 non-null  str
 25  Order City                     180519 non-null  str
 26  Order Country                  180519 non-null  str
 27  Order Customer Id              180519 non-null  int64
 28  order date (DateOrders)        180519 non-null  str
 29  Order Id                       180519 non-null  int64
 30  Order Item Cardprod Id         180519 non-null  int64
 31  Order Item Discount            180519 non-null  float64
 32  Order Item Discount Rate       180519 non-null  float64
 33  Order Item Id                  180519 non-null  int64
 34  Order Item Product Price       180519 non-null  float64
 35  Order Item Profit Ratio        180519 non-null  float64
 36  Order Item Quantity            180519 non-null  int64
 37  Sales                          180519 non-null  float64
 38  Order Item Total               180519 non-null  float64
 39  Order Profit Per Order         180519 non-null  float64
 40  Order Region                   180519 non-null  str
 41  Order State                    180519 non-null  str
 42  Order Status                   180519 non-null  str
 43  Order Zipcode                  24840 non-null   float64
 44  Product Card Id                180519 non-null  int64
 45  Product Category Id            180519 non-null  int64
 46  Product Description            0 non-null       float64
 47  Product Image                  180519 non-null  str
 48  Product Name                   180519 non-null  str
 49  Product Price                  180519 non-null  float64
 50  Product Status                 180519 non-null  int64
 51  shipping date (DateOrders)     180519 non-null  str
 52  Shipping Mode                  180519 non-null  str
dtypes: float64(15), int64(14), str(24)
memory usage: 128.3 MB

In [8]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Days for shipping (real),180519.0,3.497654,1.623722,0.000000,2.000000,3.000000,5.000000,6.000000
Days for shipment (scheduled),180519.0,2.931847,1.374449,0.000000,2.000000,4.000000,4.000000,4.000000
Benefit per order,180519.0,21.974989,104.433526,-4274.979980,7.000000,31.520000,64.800003,911.799988
Sales per customer,180519.0,183.107609,120.043670,7.490000,104.379997,163.990005,247.399994,1939.989990
Late_delivery_risk,180519.0,0.548291,0.497664,0.000000,0.000000,1.000000,1.000000,1.000000
Category Id,180519.0,31.851451,15.640064,2.000000,18.000000,29.000000,45.000000,76.000000
Customer Id,180519.0,6691.379495,4162.918106,1.000000,3258.500000,6457.000000,9779.000000,20757.000000
Customer Zipcode,180516.0,35921.126914,37542.461122,603.000000,725.000000,19380.000000,78207.000000,99205.000000
Department Id,180519.0,5.443460,1.629246,2.000000,4.000000,5.000000,7.000000,12.000000
Latitude,180519.0,29.719955,9.813646,-33.937553,18.265432,33.144863,39.279617,48.781933
Longitude,180519.0,-84.915675,21.433241,-158.025986,-98.446312,-76.847908,-66.370583,115.263077
Order Customer Id,180519.0,6691.379495,4162.918106,1.000000,3258.500000,6457.000000,9779.000000,20757.000000
Order Id,180519.0,36221.894903,21045.379569,1.000000,18057.000000,36140.000000,54144.000000,77204.000000
Order Item Cardprod Id,180519.0,692.509764,336.446807,19.000000,403.000000,627.000000,1004.000000,1363.000000
Order Item Discount,180519.0,20.664741,21.800901,0.000000,5.400000,14.000000,29.990000,500.000000
Order Item Discount Rate,180519.0,0.101668,0.070415,0.000000,0.040000,0.100000,0.160000,0.250000
Order Item Id,180519.0,90260.000000,52111.490959,1.000000,45130.500000,90260.000000,135389.500000,180519.000000
Order Item Product Price,180519.0,141.232550,139.732492,9.990000,50.000000,59.990002,199.990005,1999.989990
Order Item Profit Ratio,180519.0,0.120647,0.466796,-2.750000,0.080000,0.270000,0.360000,0.500000
Order Item Quantity,180519.0,2.127638,1.453451,1.000000,1.000000,1.000000,3.000000,5.000000
Sales,180519.0,203.772096,132.273077,9.990000,119.980003,199.919998,299.950012,1999.989990
Order Item Total,180519.0,183.107609,120.043670,7.490000,104.379997,163.990005,247.399994,1939.989990
Order Profit Per Order,180519.0,21.974989,104.433526,-4274.979980,7.000000,31.520000,64.800003,911.799988
Order Zipcode,24840.0,55426.132327,31919.279101,1040.000000,23464.000000,59405.000000,90008.000000,99301.000000
Product Card Id,180519.0,692.509764,336.446807,19.000000,403.000000,627.000000,1004.000000,1363.000000
Product Category Id,180519.0,31.851451,15.640064,2.000000,18.000000,29.000000,45.000000,76.000000
Product Description,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Product Price,180519.0,141.232550,139.732492,9.990000,50.000000,59.990002,199.990005,1999.989990
Product Status,180519.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [9]:
# checking for null values
missing = df.isnull().sum()

missing[missing > 0].sort_values(ascending=False)

Product Description    180519
Order Zipcode          155679
Customer Lname              8
Customer Zipcode            3
dtype: int64

In [10]:
# duplicate rows
df.duplicated().sum()

np.int64(0)

In [11]:
# seeing targer variable
df["Late_delivery_risk"].value_counts()
df["Late_delivery_risk"].value_counts(normalize=True) * 100

Late_delivery_risk
1    54.829132
0    45.170868
Name: proportion, dtype: float64

In [12]:
df["Delivery Status"].value_counts()

Delivery Status
Late delivery        98977
Advance shipping     41592
Shipping on time     32196
Shipping canceled     7754
Name: count, dtype: int64

In [13]:
# checking missing values properly
missing_summary = pd.DataFrame({
    "Missing Values": missing[missing > 0].sort_values(ascending=False),
    "Percentage": (missing[missing > 0].sort_values(ascending=False) / len(df)) * 100
})
missing_summary

                     Missing Values  Percentage
Product Description          180519  100.000000
Order Zipcode                155679   86.239676
Customer Lname                    8    0.004432
Customer Zipcode                  3    0.001662

In [14]:
# duplicate rows
duplicate_count = df.duplicated().sum()

print(f"Duplicate rows: {duplicate_count}")
print(f"Duplicate percentage: {duplicate_count / len(df) * 100:.2f}%")

Duplicate rows: 0
Duplicate percentage: 0.00%

In [15]:
# checking categorical columns
categorical_columns = df.select_dtypes(include=["object"]).columns

for col in categorical_columns:
    print(f"Column: {col}")
    print(df[col].nunique(), "unique values")
    print(df[col].value_counts(dropna=False).head(10))

Column: Type
4 unique values
Type
DEBIT       69295
TRANSFER    49883
PAYMENT     41725
CASH        19616
Name: count, dtype: int64
Column: Delivery Status
4 unique values
Delivery Status
Late delivery        98977
Advance shipping     41592
Shipping on time     32196
Shipping canceled     7754
Name: count, dtype: int64
Column: Category Name
50 unique values
Category Name
Cleats                  24551
Men's Footwear          22246
Women's Apparel         21035
Indoor/Outdoor Games    19298
Fishing                 17325
Water Sports            15540
Camping & Hiking        13729
Cardio Equipment        12487
Shop By Sport           10984
Electronics              3156
Name: count, dtype: int64
Column: Customer City
563 unique values
Customer City
Caguas          66770
Chicago          3885
Los Angeles      3417
Brooklyn         3412
New York         1816
Philadelphia     1577
Bronx            1500
San Diego        1437
Miami            1314
Houston          1297
Name: count, dtype: int64
Column: Customer Country
2 unique values
Customer Country
EE. UU.        111146
Puerto Rico     69373
Name: count, dtype: int64
Column: Customer Email
1 unique values
Customer Email
XXXXXXXXX    180519
Name: count, dtype: int64
Column: Customer Fname
782 unique values
Customer Fname
Mary        65150
James        1835
Robert       1759
Michael      1680
David        1625
John         1446
William      1365
Joseph       1117
Jennifer     1033
Richard      1032
Name: count, dtype: int64
Column: Customer Lname
1109 unique values
Customer Lname
Smith       64104
Johnson       989
Brown         909
Williams      869
Jones         859
Garcia        724
Wilson        675
Taylor        661
Davis         640
Moore         599
Name: count, dtype: int64
Column: Customer Password
1 unique values
Customer Password
XXXXXXXXX    180519
Name: count, dtype: int64
Column: Customer Segment
3 unique values
Customer Segment
Consumer       93504
Corporate      54789
Home Office    32226
Name: count, dtype: int64
Column: Customer State
46 unique values
Customer State
PR    69373
CA    29223
NY    11327
TX     9103
IL     7631
FL     5456
OH     4095
PA     3824
MI     3804
NJ     3191
Name: count, dtype: int64
Column: Customer Street
7458 unique values
Customer Street
9126 Wishing Expressway       122
4388 Burning Goose Ridge      117
4720 Noble Hills Wynd         116
2878 Hazy Wagon  Thicket      113
398 Emerald Grove             109
3593 Blue Brook Acres         108
2210 Merry Leaf Row           107
6289 Rocky Way                107
2585 Silent Autumn Landing    105
7694 Velvet Turnabout         103
Name: count, dtype: int64
Column: Department Name
11 unique values
Department Name
Fan Shop      66861
Apparel       48998
Golf          33220
Footwear      14525
Outdoors       9686
Fitness        2479
Discs Shop     2026
Technology     1465
Pet Shop        492
Book Shop       405
Name: count, dtype: int64
Column: Market
5 unique values
Market
LATAM           51594
Europe          50252
Pacific Asia    41260
USCA            25799
Africa          11614
Name: count, dtype: int64
Column: Order City

C:\Users\DELL\AppData\Local\Temp\ipykernel_4576\1128875176.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = df.select_dtypes(include=["object"]).columns

3597 unique values
Order City
Santo Domingo    2211
New York City    2202
Los Angeles      1845
Tegucigalpa      1783
Managua          1682
Mexico City      1484
Manila           1381
Philadelphia     1302
San Francisco    1297
London           1187
Name: count, dtype: int64
Column: Order Country
164 unique values
Order Country
Estados Unidos    24840
Francia           13222
México            13172
Alemania           9564
Australia          8497
Brasil             7987
Reino Unido        7302
China              5758
Italia             4989
India              4783
Name: count, dtype: int64
Column: order date (DateOrders)
65752 unique values
order date (DateOrders)
10/25/2016 14:39    5
3/30/2016 4:37      5
11/28/2016 1:18     5
9/8/2015 12:15      5
8/4/2017 2:31       5
7/2/2015 19:42      5
3/28/2015 0:55      5
4/10/2015 0:02      5
4/11/2017 15:49     5
3/29/2015 10:33     5
Name: count, dtype: int64
Column: Order Region
23 unique values
Order Region
Central America    28341
Western Europe     27109
South America      14935
Oceania            10148
Northern Europe     9792
Southeast Asia      9539
Southern Europe     9431
Caribbean           8318
West of USA         7993
South Asia          7731
Name: count, dtype: int64
Column: Order State
1089 unique values
Order State
Inglaterra                     6722
California                     4966
Isla de Francia                4580
Renania del Norte-Westfalia    3303
San Salvador                   3055
Nueva York                     2753
Distrito Federal               2559
Texas                          2446
Nueva Gales del Sur            2370
Santo Domingo                  2211
Name: count, dtype: int64
Column: Order Status
9 unique values
Order Status
COMPLETE           59491
PENDING_PAYMENT    39832
PROCESSING         21902
PENDING            20227
CLOSED             19616
ON_HOLD             9804
SUSPECTED_FRAUD     4062
CANCELED            3692
PAYMENT_REVIEW      1893
Name: count, dtype: int64
Column: Product Image
118 unique values
Product Image
http://images.acmesports.sports/Perfect+Fitness+Perfect+Rip+Deck                          24515
http://images.acmesports.sports/Nike+Men%27s+CJ+Elite+2+TD+Football+Cleat                 22246
http://images.acmesports.sports/Nike+Men%27s+Dri-FIT+Victory+Golf+Polo                    21035
http://images.acmesports.sports/O%27Brien+Men%27s+Neoprene+Life+Vest                      19298
http://images.acmesports.sports/Field+%26+Stream+Sportsman+16+Gun+Fire+Safe               17325
http://images.acmesports.sports/Pelican+Sunstream+100+Kayak                               15500
http://images.acmesports.sports/Diamondback+Women%27s+Serene+Classic+Comfort+Bike+2014    13729
http://images.acmesports.sports/Nike+Men%27s+Free+5.0%2B+Running+Shoe                     12169
http://images.acmesports.sports/Under+Armour+Girls%27+Toddler+Spine+Surge+Running+Shoe    10617
http://images.acmesports.sports/Fighting+video+games                                        838
Name: count, dtype: int64
Column: Product Name
118 unique values
Product Name
Perfect Fitness Perfect Rip Deck                 24515
Nike Men's CJ Elite 2 TD Football Cleat          22246
Nike Men's Dri-FIT Victory Golf Polo             21035
O'Brien Men's Neoprene Life Vest                 19298
Field & Stream Sportsman 16 Gun Fire Safe        17325
Pelican Sunstream 100 Kayak                      15500
Diamondback Women's Serene Classic Comfort Bi    13729
Nike Men's Free 5.0+ Running Shoe                12169
Under Armour Girls' Toddler Spine Surge Runni    10617
Fighting video games                               838
Name: count, dtype: int64
Column: shipping date (DateOrders)
63701 unique values
shipping date (DateOrders)
5/9/2015 18:02      10
9/27/2015 20:28     10
9/24/2015 23:48     10
8/1/2015 18:37      10
11/15/2016 13:45    10
2/26/2017 23:36     10
4/14/2017 4:26      10
2/1/2015 2:35       10
6/23/2017 4:20      10
6/5/2017 12:25      10
Name: count, dtype: int64
Column: Shipping Mode
4 unique values
Shipping Mode
Standard Class    107752
Second Class       35216
First Class        27814
Same Day            9737
Name: count, dtype: int64

In [16]:
# checking numerical columns
numerical_columns = df.select_dtypes(include=[np.number]).columns
df[numerical_columns].describe().T

,count,mean,std,min,25%,50%,75%,max
Days for shipping (real),180519.0,3.497654,1.623722,0.000000,2.000000,3.000000,5.000000,6.000000
Days for shipment (scheduled),180519.0,2.931847,1.374449,0.000000,2.000000,4.000000,4.000000,4.000000
Benefit per order,180519.0,21.974989,104.433526,-4274.979980,7.000000,31.520000,64.800003,911.799988
Sales per customer,180519.0,183.107609,120.043670,7.490000,104.379997,163.990005,247.399994,1939.989990
Late_delivery_risk,180519.0,0.548291,0.497664,0.000000,0.000000,1.000000,1.000000,1.000000
Category Id,180519.0,31.851451,15.640064,2.000000,18.000000,29.000000,45.000000,76.000000
Customer Id,180519.0,6691.379495,4162.918106,1.000000,3258.500000,6457.000000,9779.000000,20757.000000
Customer Zipcode,180516.0,35921.126914,37542.461122,603.000000,725.000000,19380.000000,78207.000000,99205.000000
Department Id,180519.0,5.443460,1.629246,2.000000,4.000000,5.000000,7.000000,12.000000
Latitude,180519.0,29.719955,9.813646,-33.937553,18.265432,33.144863,39.279617,48.781933
Longitude,180519.0,-84.915675,21.433241,-158.025986,-98.446312,-76.847908,-66.370583,115.263077
Order Customer Id,180519.0,6691.379495,4162.918106,1.000000,3258.500000,6457.000000,9779.000000,20757.000000
Order Id,180519.0,36221.894903,21045.379569,1.000000,18057.000000,36140.000000,54144.000000,77204.000000
Order Item Cardprod Id,180519.0,692.509764,336.446807,19.000000,403.000000,627.000000,1004.000000,1363.000000
Order Item Discount,180519.0,20.664741,21.800901,0.000000,5.400000,14.000000,29.990000,500.000000
Order Item Discount Rate,180519.0,0.101668,0.070415,0.000000,0.040000,0.100000,0.160000,0.250000
Order Item Id,180519.0,90260.000000,52111.490959,1.000000,45130.500000,90260.000000,135389.500000,180519.000000
Order Item Product Price,180519.0,141.232550,139.732492,9.990000,50.000000,59.990002,199.990005,1999.989990
Order Item Profit Ratio,180519.0,0.120647,0.466796,-2.750000,0.080000,0.270000,0.360000,0.500000
Order Item Quantity,180519.0,2.127638,1.453451,1.000000,1.000000,1.000000,3.000000,5.000000
Sales,180519.0,203.772096,132.273077,9.990000,119.980003,199.919998,299.950012,1999.989990
Order Item Total,180519.0,183.107609,120.043670,7.490000,104.379997,163.990005,247.399994,1939.989990
Order Profit Per Order,180519.0,21.974989,104.433526,-4274.979980,7.000000,31.520000,64.800003,911.799988
Order Zipcode,24840.0,55426.132327,31919.279101,1040.000000,23464.000000,59405.000000,90008.000000,99301.000000
Product Card Id,180519.0,692.509764,336.446807,19.000000,403.000000,627.000000,1004.000000,1363.000000
Product Category Id,180519.0,31.851451,15.640064,2.000000,18.000000,29.000000,45.000000,76.000000
Product Description,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Product Price,180519.0,141.232550,139.732492,9.990000,50.000000,59.990002,199.990005,1999.989990
Product Status,180519.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [17]:
# understanding dates
date_candidates = [
    col for col in df.columns if "date" in col.lower() or "time" in col.lower()
]

date_candidates

['order date (DateOrders)', 'shipping date (DateOrders)']

In [18]:
for col in date_candidates:
    print(f"Column: {col}")
    print(df[col].nunique(), "unique values")
    print(df[col].value_counts(dropna=False).head(10))

Column: order date (DateOrders)
65752 unique values
order date (DateOrders)
10/25/2016 14:39    5
3/30/2016 4:37      5
11/28/2016 1:18     5
9/8/2015 12:15      5
8/4/2017 2:31       5
7/2/2015 19:42      5
3/28/2015 0:55      5
4/10/2015 0:02      5
4/11/2017 15:49     5
3/29/2015 10:33     5
Name: count, dtype: int64
Column: shipping date (DateOrders)
63701 unique values
shipping date (DateOrders)
5/9/2015 18:02      10
9/27/2015 20:28     10
9/24/2015 23:48     10
8/1/2015 18:37      10
11/15/2016 13:45    10
2/26/2017 23:36     10
4/14/2017 4:26      10
2/1/2015 2:35       10
6/23/2017 4:20      10
6/5/2017 12:25      10
Name: count, dtype: int64

In [19]:
# checking losistics variables
logistics_columns = [
    "Days for shipping (real)",
    "Days for shipment (scheduled)",
    "Shipping Mode",
    "Delivery Status",
    "Late_delivery_risk",
    "Order Status"
]

df[logistics_columns].head()

,Days for shipping (real),Days for shipment (scheduled),Shipping Mode,Delivery Status,Late_delivery_risk,Order Status
0,3,4,Standard Class,Advance shipping,0,COMPLETE
1,5,4,Standard Class,Late delivery,1,PENDING
2,4,4,Standard Class,Shipping on time,0,CLOSED
3,3,4,Standard Class,Advance shipping,0,COMPLETE
4,2,4,Standard Class,Advance shipping,0,PENDING_PAYMENT

In [20]:
df[logistics_columns].describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Days for shipping (real),180519.0,NaN,NaN,NaN,3.497654,1.623722,0.0,2.0,3.0,5.0,6.0
Days for shipment (scheduled),180519.0,NaN,NaN,NaN,2.931847,1.374449,0.0,2.0,4.0,4.0,4.0
Shipping Mode,180519,4,Standard Class,107752,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Delivery Status,180519,4,Late delivery,98977,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Late_delivery_risk,180519.0,NaN,NaN,NaN,0.548291,0.497664,0.0,0.0,1.0,1.0,1.0
Order Status,180519,9,COMPLETE,59491,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
df[[
    "Days for shipping (real)",
    "Days for shipment (scheduled)"
]].describe().T

,count,mean,std,min,25%,50%,75%,max
Days for shipping (real),180519.0,3.497654,1.623722,0.0,2.0,3.0,5.0,6.0
Days for shipment (scheduled),180519.0,2.931847,1.374449,0.0,2.0,4.0,4.0,4.0

In [22]:
pd.crosstab(
    df["Late_delivery_risk"],
    df["Shipping Mode"],
    normalize="columns"
) * 100

Shipping Mode       First Class   Same Day  Second Class  Standard Class
Late_delivery_risk
0                      4.677501  54.256958     23.367219       61.928317
1                     95.322499  45.743042     76.632781       38.071683

In [23]:
# counting ? values in each column
question_mark_counts = (df == "?").sum()

question_mark_counts[question_mark_counts > 0].sort_values(ascending=False)

question_mark_counts

Type                             0
Days for shipping (real)         0
Days for shipment (scheduled)    0
Benefit per order                0
Sales per customer               0
Delivery Status                  0
Late_delivery_risk               0
Category Id                      0
Category Name                    0
Customer City                    0
Customer Country                 0
Customer Email                   0
Customer Fname                   0
Customer Id                      0
Customer Lname                   0
Customer Password                0
Customer Segment                 0
Customer State                   0
Customer Street                  0
Customer Zipcode                 0
Department Id                    0
Department Name                  0
Latitude                         0
Longitude                        0
Market                           0
Order City                       0
Order Country                    0
Order Customer Id                0
order date (DateOrders)          0
Order Id                         0
Order Item Cardprod Id           0
Order Item Discount              0
Order Item Discount Rate         0
Order Item Id                    0
Order Item Product Price         0
Order Item Profit Ratio          0
Order Item Quantity              0
Sales                            0
Order Item Total                 0
Order Profit Per Order           0
Order Region                     0
Order State                      0
Order Status                     0
Order Zipcode                    0
Product Card Id                  0
Product Category Id              0
Product Description              0
Product Image                    0
Product Name                     0
Product Price                    0
Product Status                   0
shipping date (DateOrders)       0
Shipping Mode                    0
dtype: int64

In [24]:
# checking empty strings in each column
empty_string_counts = (df == "").sum()
empty_string_counts[empty_string_counts > 0].sort_values(ascending=False)

empty_string_counts

Type                             0
Days for shipping (real)         0
Days for shipment (scheduled)    0
Benefit per order                0
Sales per customer               0
Delivery Status                  0
Late_delivery_risk               0
Category Id                      0
Category Name                    0
Customer City                    0
Customer Country                 0
Customer Email                   0
Customer Fname                   0
Customer Id                      0
Customer Lname                   0
Customer Password                0
Customer Segment                 0
Customer State                   0
Customer Street                  0
Customer Zipcode                 0
Department Id                    0
Department Name                  0
Latitude                         0
Longitude                        0
Market                           0
Order City                       0
Order Country                    0
Order Customer Id                0
order date (DateOrders)          0
Order Id                         0
Order Item Cardprod Id           0
Order Item Discount              0
Order Item Discount Rate         0
Order Item Id                    0
Order Item Product Price         0
Order Item Profit Ratio          0
Order Item Quantity              0
Sales                            0
Order Item Total                 0
Order Profit Per Order           0
Order Region                     0
Order State                      0
Order Status                     0
Order Zipcode                    0
Product Card Id                  0
Product Category Id              0
Product Description              0
Product Image                    0
Product Name                     0
Product Price                    0
Product Status                   0
shipping date (DateOrders)       0
Shipping Mode                    0
dtype: int64

In [25]:
# creating working dataset
df_clean = df.copy()

In [26]:
df_clean.isnull().sum().sort_values(ascending=False).head(20)

Product Description              180519
Order Zipcode                    155679
Customer Lname                        8
Customer Zipcode                      3
Days for shipment (scheduled)         0
Sales per customer                    0
Benefit per order                     0
Delivery Status                       0
Late_delivery_risk                    0
Customer City                         0
Customer Country                      0
Category Id                           0
Category Name                         0
Customer Fname                        0
Customer Email                        0
Customer Password                     0
Customer Id                           0
Customer Segment                      0
Customer State                        0
Days for shipping (real)              0
dtype: int64

In [27]:
df_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 53 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Type                           180519 non-null  str
 1   Days for shipping (real)       180519 non-null  int64
 2   Days for shipment (scheduled)  180519 non-null  int64
 3   Benefit per order              180519 non-null  float64
 4   Sales per customer             180519 non-null  float64
 5   Delivery Status                180519 non-null  str
 6   Late_delivery_risk             180519 non-null  int64
 7   Category Id                    180519 non-null  int64
 8   Category Name                  180519 non-null  str
 9   Customer City                  180519 non-null  str
 10  Customer Country               180519 non-null  str
 11  Customer Email                 180519 non-null  str
 12  Customer Fname                 180519 non-null  str
 13  Customer Id                    180519 non-null  int64
 14  Customer Lname                 180511 non-null  str
 15  Customer Password              180519 non-null  str
 16  Customer Segment               180519 non-null  str
 17  Customer State                 180519 non-null  str
 18  Customer Street                180519 non-null  str
 19  Customer Zipcode               180516 non-null  float64
 20  Department Id                  180519 non-null  int64
 21  Department Name                180519 non-null  str
 22  Latitude                       180519 non-null  float64
 23  Longitude                      180519 non-null  float64
 24  Market                         180519 non-null  str
 25  Order City                     180519 non-null  str
 26  Order Country                  180519 non-null  str
 27  Order Customer Id              180519 non-null  int64
 28  order date (DateOrders)        180519 non-null  str
 29  Order Id                       180519 non-null  int64
 30  Order Item Cardprod Id         180519 non-null  int64
 31  Order Item Discount            180519 non-null  float64
 32  Order Item Discount Rate       180519 non-null  float64
 33  Order Item Id                  180519 non-null  int64
 34  Order Item Product Price       180519 non-null  float64
 35  Order Item Profit Ratio        180519 non-null  float64
 36  Order Item Quantity            180519 non-null  int64
 37  Sales                          180519 non-null  float64
 38  Order Item Total               180519 non-null  float64
 39  Order Profit Per Order         180519 non-null  float64
 40  Order Region                   180519 non-null  str
 41  Order State                    180519 non-null  str
 42  Order Status                   180519 non-null  str
 43  Order Zipcode                  24840 non-null   float64
 44  Product Card Id                180519 non-null  int64
 45  Product Category Id            180519 non-null  int64
 46  Product Description            0 non-null       float64
 47  Product Image                  180519 non-null  str
 48  Product Name                   180519 non-null  str
 49  Product Price                  180519 non-null  float64
 50  Product Status                 180519 non-null  int64
 51  shipping date (DateOrders)     180519 non-null  str
 52  Shipping Mode                  180519 non-null  str
dtypes: float64(15), int64(14), str(24)
memory usage: 128.3 MB

In [28]:
# converting date columns to datetime type
df_clean[date_candidates] = df_clean[date_candidates].apply(pd.to_datetime, errors="coerce")

In [29]:
df_clean[
    ["order date (DateOrders)", "shipping date (DateOrders)"]
].dtypes

order date (DateOrders)       datetime64[us]
shipping date (DateOrders)    datetime64[us]
dtype: object

In [30]:
# checking numerical columns that matters
numeric_check = [
    "Days for shipping (real)",
    "Days for shipment (scheduled)",
    "Benefit per order",
    "Sales",
    "Order Item Quantity",
    "Order Item Product Price",
    "Order Item Total"
]

df_clean[numeric_check].dtypes

Days for shipping (real)           int64
Days for shipment (scheduled)      int64
Benefit per order                float64
Sales                            float64
Order Item Quantity                int64
Order Item Product Price         float64
Order Item Total                 float64
dtype: object

In [31]:
df_clean[
    [
        "Days for shipping (real)",
        "Days for shipment (scheduled)"
    ]
].describe()

       Days for shipping (real)  Days for shipment (scheduled)
count             180519.000000                  180519.000000
mean                   3.497654                       2.931847
std                    1.623722                       1.374449
min                    0.000000                       0.000000
25%                    2.000000                       2.000000
50%                    3.000000                       4.000000
75%                    5.000000                       4.000000
max                    6.000000                       4.000000

In [32]:
(df_clean["Days for shipping (real)"] < 0).sum()
(df_clean["Days for shipment (scheduled)"] < 0).sum()

np.int64(0)

In [33]:
# checking target
df_clean["Late_delivery_risk"].value_counts(dropna=False)
df_clean["Late_delivery_risk"].isnull().sum()

np.int64(0)

## Initial Data Cleaning

The dataset was reviewed for missingness, irrelevant fields, sensitive information, and data usability. Variables with complete missingness, excessive missingness, or no analytical relevance to the logistics problem are removed from the working dataset.

In [34]:
columns_to_drop = [
    "Product Description",
    "Order Zipcode",
    "Customer Password",
]

df_clean.drop(columns=columns_to_drop, inplace=True)
df_clean.shape

(180519, 50)

In [35]:
df_clean.isnull().sum().sort_values(ascending=False).head(20)

Customer Lname                   8
Customer Zipcode                 3
Days for shipping (real)         0
Days for shipment (scheduled)    0
Sales per customer               0
Benefit per order                0
Late_delivery_risk               0
Category Id                      0
Category Name                    0
Delivery Status                  0
Customer City                    0
Customer Country                 0
Customer Fname                   0
Customer Email                   0
Customer Id                      0
Customer Segment                 0
Customer State                   0
Type                             0
Customer Street                  0
Department Id                    0
dtype: int64

In [36]:
df_clean.columns.to_list()

['Type',
 'Days for shipping (real)',
 'Days for shipment (scheduled)',
 'Benefit per order',
 'Sales per customer',
 'Delivery Status',
 'Late_delivery_risk',
 'Category Id',
 'Category Name',
 'Customer City',
 'Customer Country',
 'Customer Email',
 'Customer Fname',
 'Customer Id',
 'Customer Lname',
 'Customer Segment',
 'Customer State',
 'Customer Street',
 'Customer Zipcode',
 'Department Id',
 'Department Name',
 'Latitude',
 'Longitude',
 'Market',
 'Order City',
 'Order Country',
 'Order Customer Id',
 'order date (DateOrders)',
 'Order Id',
 'Order Item Cardprod Id',
 'Order Item Discount',
 'Order Item Discount Rate',
 'Order Item Id',
 'Order Item Product Price',
 'Order Item Profit Ratio',
 'Order Item Quantity',
 'Sales',
 'Order Item Total',
 'Order Profit Per Order',
 'Order Region',
 'Order State',
 'Order Status',
 'Product Card Id',
 'Product Category Id',
 'Product Image',
 'Product Name',
 'Product Price',
 'Product Status',
 'shipping date (DateOrders)',
 'Shipping Mode']

In [37]:
df_clean.duplicated().sum()

np.int64(0)

In [38]:
df_clean["Order Id"].nunique()

65752

In [39]:
df_clean["Order Item Id"].nunique()

180519

In [40]:
df_clean.shape

(180519, 50)

In [41]:
# understanding order structure
items_per_order = df_clean.groupby("Order Id")["Order Item Id"].count()
items_per_order.describe()

count    65752.000000
mean         2.745453
std          1.478363
min          1.000000
25%          1.000000
50%          3.000000
75%          4.000000
max          5.000000
Name: Order Item Id, dtype: float64

In [42]:
items_per_order.value_counts().sort_index().head(20)

Order Item Id
1    19850
2    11447
3    11398
4    11704
5    11353
Name: count, dtype: int64

In [43]:
items_per_order.max()

np.int64(5)

In [44]:
# checking How many shipments are at late-delivery risk?
late_risk_rate = df_clean["Late_delivery_risk"].mean() * 100
print(f"Percentage of shipments at late-delivery risk: {late_risk_rate:.2f}%")

Percentage of shipments at late-delivery risk: 54.83%

In [45]:
# checking distribution
df_clean["Late_delivery_risk"].value_counts(normalize=True).sort_index() * 100

Late_delivery_risk
0    45.170868
1    54.829132
Name: proportion, dtype: float64

In [46]:
# checking highest modes have late-delivery risk
shipping_mode_risk = (
    df_clean.groupby("Shipping Mode")["Late_delivery_risk"]
    .mean()
    .mul(100)
    .sort_values(ascending=False)
)

shipping_mode_risk

Shipping Mode
First Class       95.322499
Second Class      76.632781
Same Day          45.743042
Standard Class    38.071683
Name: Late_delivery_risk, dtype: float64

In [47]:
# actual vs scheduled shipping days
df_clean.groupby("Shipping Mode")[["Days for shipping (real)", "Days for shipment (scheduled)"]].mean().sort_values(by="Days for shipping (real)", ascending=False)

                Days for shipping (real)  Days for shipment (scheduled)
Shipping Mode
Standard Class                  3.995907                            4.0
Second Class                    3.990828                            2.0
First Class                     2.000000                            1.0
Same Day                        0.478279                            0.0

In [48]:
pd.crosstab(
    df_clean["Late_delivery_risk"],
    df_clean["Delivery Status"],
    normalize="index"
) * 100

Delivery Status,Advance shipping,Late delivery,Shipping canceled,Shipping on time
Late_delivery_risk,,,,
0,51.006843,0.0,9.50921,39.483947
1,0.000000,100.0,0.00000,0.000000

In [49]:
pd.crosstab(
    df_clean["Late_delivery_risk"],
    df_clean["Shipping Mode"],
    normalize="index"
) * 100

Shipping Mode       First Class  Same Day  Second Class  Standard Class
Late_delivery_risk
0                      1.595497  6.478870     10.091732       81.833902
1                     26.787031  4.500035     27.265930       41.447003

In [50]:
df_clean.groupby("Late_delivery_risk")[
    ["Days for shipping (real)", "Days for shipment (scheduled)"]
].mean()

                    Days for shipping (real)  Days for shipment (scheduled)
Late_delivery_risk
0                                   2.779561                       3.491146
1                                   4.089253                       2.471069

In [51]:
# calculating the difference between actual and scheduled shipping days
df_clean["shipping_delay_days"] = (df_clean["Days for shipping (real)"] - df_clean["Days for shipment (scheduled)"])
df_clean.groupby("Late_delivery_risk")["shipping_delay_days"].describe()

                      count      mean       std  min  25%  50%  75%  max
Late_delivery_risk
0                   81542.0 -0.711584  0.999927 -2.0 -2.0 -1.0  0.0  4.0
1                   98977.0  1.618184  0.882527  1.0  1.0  1.0  2.0  4.0

### Prediction Leakage Note

`Delivery Status`, `Days for shipping (real)`, and the derived `shipping_delay_days` contain information that becomes available after or during the shipment outcome. These variables will therefore not be used as predictors in the primary early-stage shipment-delay prediction model.

They may still be used for retrospective logistics performance analysis and KPI development.

In [52]:
# checking missing values in clean working dataset

missing_values = df_clean.isnull().sum()

missing_summary = missing_values[missing_values > 0].sort_values(ascending=False)

print("Columns with missing values:")
print(missing_summary)

print("\nTotal missing values:", missing_values.sum())
print("Dataset shape:", df_clean.shape)

Columns with missing values:
Customer Lname      8
Customer Zipcode    3
dtype: int64

Total missing values: 11
Dataset shape: (180519, 51)

In [53]:
# inspect rows with missing customer information

missing_customer_info = df_clean[
    df_clean["Customer Lname"].isnull() | df_clean["Customer Zipcode"].isnull() ]

display(missing_customer_info[["Customer Lname", "Customer Zipcode"]])

print("Number of rows with missing customer information:", len(missing_customer_info))

       Customer Lname  Customer Zipcode
35704         Foreman               NaN
41422             NaN             725.0
46440          Slater               NaN
50447             NaN           60067.0
82511         Elliott               NaN
86260             NaN           90027.0
92621             NaN             725.0
97530             NaN           78240.0
120404            NaN           28314.0
166129            NaN           96822.0
167119            NaN           91335.0

Number of rows with missing customer information: 11

In [54]:
# Verify that we have preserved all rows

print("Dataset shape:", df_clean.shape)
print("Total missing values:", df_clean.isnull().sum().sum())
print("Duplicate rows:", df_clean.duplicated().sum())

Dataset shape: (180519, 51)
Total missing values: 11
Duplicate rows: 0

In [55]:
# Inspect data types of all columns

print(df_clean.dtypes.to_string())

Type                                        str
Days for shipping (real)                  int64
Days for shipment (scheduled)             int64
Benefit per order                       float64
Sales per customer                      float64
Delivery Status                             str
Late_delivery_risk                        int64
Category Id                               int64
Category Name                               str
Customer City                               str
Customer Country                            str
Customer Email                              str
Customer Fname                              str
Customer Id                               int64
Customer Lname                              str
Customer Segment                            str
Customer State                              str
Customer Street                             str
Customer Zipcode                        float64
Department Id                             int64
Department Name                             str
Latitude                                float64
Longitude                               float64
Market                                      str
Order City                                  str
Order Country                               str
Order Customer Id                         int64
order date (DateOrders)          datetime64[us]
Order Id                                  int64
Order Item Cardprod Id                    int64
Order Item Discount                     float64
Order Item Discount Rate                float64
Order Item Id                             int64
Order Item Product Price                float64
Order Item Profit Ratio                 float64
Order Item Quantity                       int64
Sales                                   float64
Order Item Total                        float64
Order Profit Per Order                  float64
Order Region                                str
Order State                                 str
Order Status                                str
Product Card Id                           int64
Product Category Id                       int64
Product Image                               str
Product Name                                str
Product Price                           float64
Product Status                            int64
shipping date (DateOrders)       datetime64[us]
Shipping Mode                               str
shipping_delay_days                       int64

In [56]:
# Check date columns

date_columns = [
    "order date (DateOrders)",
    "shipping date (DateOrders)"
]

for col in date_columns:
    print(f"\nColumn: {col}")
    print("Data type:", df_clean[col].dtype)
    print("Missing values:", df_clean[col].isnull().sum())
    print("Sample values:")
    print(df_clean[col].head())

Column: order date (DateOrders)
Data type: datetime64[us]
Missing values: 0
Sample values:
0   2018-01-31 22:56:00
1   2018-01-13 12:27:00
2   2018-01-13 12:06:00
3   2018-01-13 11:45:00
4   2018-01-13 11:24:00
Name: order date (DateOrders), dtype: datetime64[us]

Column: shipping date (DateOrders)
Data type: datetime64[us]
Missing values: 0
Sample values:
0   2018-02-03 22:56:00
1   2018-01-18 12:27:00
2   2018-01-17 12:06:00
3   2018-01-16 11:45:00
4   2018-01-15 11:24:00
Name: shipping date (DateOrders), dtype: datetime64[us]

In [57]:
# Check shipping duration columns

duration_columns = [
    "Days for shipping (real)",
    "Days for shipment (scheduled)"
]

for col in duration_columns:
    print(f"\n{col}")
    print("Minimum:", df_clean[col].min())
    print("Maximum:", df_clean[col].max())
    print("Negative values:", (df_clean[col] < 0).sum())
    print("Missing values:", df_clean[col].isnull().sum())

Days for shipping (real)
Minimum: 0
Maximum: 6
Negative values: 0
Missing values: 0

Days for shipment (scheduled)
Minimum: 0
Maximum: 4
Negative values: 0
Missing values: 0

In [58]:
# Inspect numerical columns

numeric_columns = df_clean.select_dtypes(
    include="number"
).columns

print("Number of numerical columns:", len(numeric_columns))

display(
    df_clean[numeric_columns].describe().T.round(2)
)

Number of numerical columns: 28

,count,mean,std,min,25%,50%,75%,max
Days for shipping (real),180519.0,3.50,1.62,0.00,2.00,3.00,5.00,6.00
Days for shipment (scheduled),180519.0,2.93,1.37,0.00,2.00,4.00,4.00,4.00
Benefit per order,180519.0,21.97,104.43,-4274.98,7.00,31.52,64.80,911.80
Sales per customer,180519.0,183.11,120.04,7.49,104.38,163.99,247.40,1939.99
Late_delivery_risk,180519.0,0.55,0.50,0.00,0.00,1.00,1.00,1.00
Category Id,180519.0,31.85,15.64,2.00,18.00,29.00,45.00,76.00
Customer Id,180519.0,6691.38,4162.92,1.00,3258.50,6457.00,9779.00,20757.00
Customer Zipcode,180516.0,35921.13,37542.46,603.00,725.00,19380.00,78207.00,99205.00
Department Id,180519.0,5.44,1.63,2.00,4.00,5.00,7.00,12.00
Latitude,180519.0,29.72,9.81,-33.94,18.27,33.14,39.28,48.78
Longitude,180519.0,-84.92,21.43,-158.03,-98.45,-76.85,-66.37,115.26
Order Customer Id,180519.0,6691.38,4162.92,1.00,3258.50,6457.00,9779.00,20757.00
Order Id,180519.0,36221.89,21045.38,1.00,18057.00,36140.00,54144.00,77204.00
Order Item Cardprod Id,180519.0,692.51,336.45,19.00,403.00,627.00,1004.00,1363.00
Order Item Discount,180519.0,20.66,21.80,0.00,5.40,14.00,29.99,500.00
Order Item Discount Rate,180519.0,0.10,0.07,0.00,0.04,0.10,0.16,0.25
Order Item Id,180519.0,90260.00,52111.49,1.00,45130.50,90260.00,135389.50,180519.00
Order Item Product Price,180519.0,141.23,139.73,9.99,50.00,59.99,199.99,1999.99
Order Item Profit Ratio,180519.0,0.12,0.47,-2.75,0.08,0.27,0.36,0.50
Order Item Quantity,180519.0,2.13,1.45,1.00,1.00,1.00,3.00,5.00
Sales,180519.0,203.77,132.27,9.99,119.98,199.92,299.95,1999.99
Order Item Total,180519.0,183.11,120.04,7.49,104.38,163.99,247.40,1939.99
Order Profit Per Order,180519.0,21.97,104.43,-4274.98,7.00,31.52,64.80,911.80
Product Card Id,180519.0,692.51,336.45,19.00,403.00,627.00,1004.00,1363.00
Product Category Id,180519.0,31.85,15.64,2.00,18.00,29.00,45.00,76.00
Product Price,180519.0,141.23,139.73,9.99,50.00,59.99,199.99,1999.99
Product Status,180519.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00
shipping_delay_days,180519.0,0.57,1.49,-2.00,0.00,1.00,1.00,4.00

In [59]:
# Detect potential outliers using the IQR method

columns_to_check = [
    "Benefit per order",
    "Sales per customer",
    "Order Item Product Price",
    "Order Item Discount",
    "Order Item Total",
    "shipping_delay_days"
]

outlier_results = []

for col in columns_to_check:
    q1 = df_clean[col].quantile(0.25)
    q3 = df_clean[col].quantile(0.75)
    iqr = q3 - q1

    lower_bound = q1 - 1.5 * iqr
    upper_bound = q3 + 1.5 * iqr

    outlier_mask = (
        (df_clean[col] < lower_bound)
        | (df_clean[col] > upper_bound)
    )

    outlier_results.append({
        "Column": col,
        "Q1": round(q1, 2),
        "Q3": round(q3, 2),
        "IQR": round(iqr, 2),
        "Lower Bound": round(lower_bound, 2),
        "Upper Bound": round(upper_bound, 2),
        "Potential Outliers": int(outlier_mask.sum()),
        "Outlier Percentage": round(
            outlier_mask.mean() * 100, 2
        )
    })

outlier_summary = pd.DataFrame(outlier_results)

display(outlier_summary)

,Column,Q1,Q3,IQR,Lower Bound,Upper Bound,Potential Outliers,Outlier Percentage
0,Benefit per order,7.00,64.80,57.80,-79.70,151.50,18942,10.49
1,Sales per customer,104.38,247.40,143.02,-110.15,461.93,1943,1.08
2,Order Item Product Price,50.00,199.99,149.99,-174.99,424.98,2048,1.13
3,Order Item Discount,5.40,29.99,24.59,-31.48,66.87,7537,4.18
4,Order Item Total,104.38,247.40,143.02,-110.15,461.93,1943,1.08
5,shipping_delay_days,0.00,1.00,1.00,-1.50,2.50,35701,19.78

In [60]:
# Count each observed shipping-delay value

delay_distribution = (
    df_clean["shipping_delay_days"]
    .value_counts()
    .sort_index()
    .rename_axis("Shipping Delay (Days)")
    .reset_index(name="Number of Records")
)

delay_distribution["Percentage"] = (
    delay_distribution["Number of Records"]
    / len(df_clean) * 100
).round(2)

display(delay_distribution)

   Shipping Delay (Days)  Number of Records  Percentage
0                     -2              21666       12.00
1                     -1              21700       12.02
2                      0              33753       18.70
3                      1              60647       33.60
4                      2              28718       15.91
5                      3               7052        3.91
6                      4               6983        3.87

In [61]:
# Validate the shipping-delay distribution

print("Total records:", delay_distribution["Number of Records"].sum())
print("Dataset records:", len(df_clean))

print(
    "Percentages total:",
    round(delay_distribution["Percentage"].sum(), 2),
    "%"
)

Total records: 180519
Dataset records: 180519
Percentages total: 100.01 %

In [62]:
# Review the cleaned dataset's columns

print("Number of columns:", len(df_clean.columns))

for i, col in enumerate(df_clean.columns, start=1):
    print(f"{i}. {col}")

Number of columns: 51
1. Type
2. Days for shipping (real)
3. Days for shipment (scheduled)
4. Benefit per order
5. Sales per customer
6. Delivery Status
7. Late_delivery_risk
8. Category Id
9. Category Name
10. Customer City
11. Customer Country
12. Customer Email
13. Customer Fname
14. Customer Id
15. Customer Lname
16. Customer Segment
17. Customer State
18. Customer Street
19. Customer Zipcode
20. Department Id
21. Department Name
22. Latitude
23. Longitude
24. Market
25. Order City
26. Order Country
27. Order Customer Id
28. order date (DateOrders)
29. Order Id
30. Order Item Cardprod Id
31. Order Item Discount
32. Order Item Discount Rate
33. Order Item Id
34. Order Item Product Price
35. Order Item Profit Ratio
36. Order Item Quantity
37. Sales
38. Order Item Total
39. Order Profit Per Order
40. Order Region
41. Order State
42. Order Status
43. Product Card Id
44. Product Category Id
45. Product Image
46. Product Name
47. Product Price
48. Product Status
49. shipping date (DateOrders)
50. Shipping Mode
51. shipping_delay_days

In [63]:
# Compare the existing risk label with delivery status

print("Delivery Status values:")
print(df_clean["Delivery Status"].value_counts(dropna=False))

print("\nLate delivery risk values:")
print(df_clean["Late_delivery_risk"].value_counts(dropna=False))

print("\nCross-tabulation:")
display(
    pd.crosstab(
        df_clean["Delivery Status"],
        df_clean["Late_delivery_risk"],
        margins=True
    )
)

Delivery Status values:
Delivery Status
Late delivery        98977
Advance shipping     41592
Shipping on time     32196
Shipping canceled     7754
Name: count, dtype: int64

Late delivery risk values:
Late_delivery_risk
1    98977
0    81542
Name: count, dtype: int64

Cross-tabulation:

Late_delivery_risk      0      1     All
Delivery Status
Advance shipping    41592      0   41592
Late delivery           0  98977   98977
Shipping canceled    7754      0    7754
Shipping on time    32196      0   32196
All                 81542  98977  180519

In [64]:
from pathlib import Path

# Save the cleaned dataset
output_path = Path("../data/processed/DataCoSupplyChain_cleaned.csv")

# Create the processed folder if it doesn't exist
output_path.parent.mkdir(parents=True, exist_ok=True)

# Export the cleaned dataframe
df_clean.to_csv(output_path, index=False)

print("Cleaned dataset saved successfully!")
print("File path:", output_path)
print("Dataset shape:", df_clean.shape)

Cleaned dataset saved successfully!
File path: ..\data\processed\DataCoSupplyChain_cleaned.csv
Dataset shape: (180519, 51)

In [65]:
# verifying saved data

from pathlib import Path
import pandas as pd

# Locate the saved cleaned dataset
file_path = Path("../data/processed/DataCoSupplyChain_cleaned.csv")

# Verify the file exists
if file_path.exists():
    df_check = pd.read_csv(file_path)

    print("File exists: Yes")
    print("Dataset shape:", df_check.shape)
    print("Duplicate rows:", df_check.duplicated().sum())
    print("Total missing values:", df_check.isnull().sum().sum())
    print("\nFirst five rows:")
    display(df_check.head())
else:
    print("File not found. Check the file path.")

File exists: Yes
Dataset shape: (180519, 51)
Duplicate rows: 0
Total missing values: 11

First five rows:

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,Customer Country,Customer Email,Customer Fname,Customer Id,Customer Lname,Customer Segment,Customer State,Customer Street,Customer Zipcode,Department Id,Department Name,Latitude,Longitude,Market,Order City,Order Country,Order Customer Id,order date (DateOrders),Order Id,Order Item Cardprod Id,Order Item Discount,Order Item Discount Rate,Order Item Id,Order Item Product Price,Order Item Profit Ratio,Order Item Quantity,Sales,Order Item Total,Order Profit Per Order,Order Region,Order State,Order Status,Product Card Id,Product Category Id,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode,shipping_delay_days
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,Puerto Rico,XXXXXXXXX,Cally,20755,Holloway,Consumer,PR,5365 Noble Nectar Island,725.0,2,Fitness,18.251453,-66.037056,Pacific Asia,Bekasi,Indonesia,20755,2018-01-31 22:56:00,77202,1360,13.110000,0.04,180517,327.75,0.29,1,327.75,314.640015,91.250000,Southeast Asia,Java Occidental,COMPLETE,1360,73,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2018-02-03 22:56:00,Standard Class,-1
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,Puerto Rico,XXXXXXXXX,Irene,19492,Luna,Consumer,PR,2679 Rustic Loop,725.0,2,Fitness,18.279451,-66.037064,Pacific Asia,Bikaner,India,19492,2018-01-13 12:27:00,75939,1360,16.389999,0.05,179254,327.75,-0.80,1,327.75,311.359985,-249.089996,South Asia,Rajastán,PENDING,1360,73,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2018-01-18 12:27:00,Standard Class,1
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,EE. UU.,XXXXXXXXX,Gillian,19491,Maldonado,Consumer,CA,8510 Round Bear Gate,95125.0,2,Fitness,37.292233,-121.881279,Pacific Asia,Bikaner,India,19491,2018-01-13 12:06:00,75938,1360,18.030001,0.06,179253,327.75,-0.80,1,327.75,309.720001,-247.779999,South Asia,Rajastán,CLOSED,1360,73,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2018-01-17 12:06:00,Standard Class,0
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,EE. UU.,XXXXXXXXX,Tana,19490,Tate,Home Office,CA,3200 Amber Bend,90027.0,2,Fitness,34.125946,-118.291016,Pacific Asia,Townsville,Australia,19490,2018-01-13 11:45:00,75937,1360,22.940001,0.07,179252,327.75,0.08,1,327.75,304.809998,22.860001,Oceania,Queensland,COMPLETE,1360,73,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2018-01-16 11:45:00,Standard Class,-1
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,Puerto Rico,XXXXXXXXX,Orli,19489,Hendricks,Corporate,PR,8671 Iron Anchor Corners,725.0,2,Fitness,18.253769,-66.037048,Pacific Asia,Townsville,Australia,19489,2018-01-13 11:24:00,75936,1360,29.500000,0.09,179251,327.75,0.45,1,327.75,298.250000,134.210007,Oceania,Queensland,PENDING_PAYMENT,1360,73,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2018-01-15 11:24:00,Standard Class,-2